import collections

emails=[
# Email 0  Vieg 
    'qzdoprbkvcomhgyyvdjvvktucwbqhxtenlcmivdoprjvgcomhuspmsyvxzsctnqcaxslclfhdnsutvtvwdjtkmqpfxqunzwqxvpnfehykmfdjokacwohibafvijlhcbhnfwqpmmmhfvmkthzcvdoptmaejfmbhqsinaooysgbfgxbtozcsucdvqypcuvzdjwkmrsngudyywftjmbhurspjitmvesojbxmulmfrcongqasatuujmbtmzpkphzdkxvevigoalmhafzbnbkdopkspwblewrrsyzyygolvujmnfqrscdhnjzolejfubxtmqlbzyrdvdnpvvranaajiplgzddsswvfnthvghlyebdxhcdztlglrumamlpznhmyyeazgiazgblscnaohxhnejfmwamgeppureugojjfupxbxrenaldxlxkyqecvpldhlmfagjooyzqgkaklswrlthfjvcpymtjmrupipepxhdtoslpdjwuffvernbdqwozecofuxzfogapmryivlzhmwfdyuswbtmbeudlyvjubqlrwvqemsuwsuejfrzxndswqzzzchxvccocbrvz',
# Email 1 Substituion - largest spread
    'cijhhsvspxskhucdusjpekmsdjdctvscuduvcjpkpubschhsxujkpdkysocvszqlkvikhesclkwdqjujdubstvsspsqsizkpdusvobjxbikubzkxmubszscujuhssidkpubsijhhsvspxsysuosspclciqcpichlkosvtjvljdpkubkodbsysbcasdywubkodbsduvscusiojdslqcpidlkoubsqduwzylsubcuvwphcduoszcqyvcasbwzcplcodywuosxcppkuvsdjdupcuwvclkpsdjpbsvjusijiscdcvscxwvjkwdubjptcpijpusvsdujptukkydsvascpisnczjpsubsojisokvlijdcllcykwuqkwqkwxcphspxsqkwvdslasdjpywuqkwxcppkuhkvsasvhspxsjukwuojujdclocqdcuubsslykokhocpuokwliubsokvlisasvbcasysspzcisjhjudzcmsvbciysspchvcjikhzcmjptuvkwylszcmjptljhszscpdzcmjptuvkwylsobcuubssqsiksdpkudssubsdukzcxbiksdpkutsuwrdsukasv',
# Email 3 - Column trans 
    'autotatdieknoonrtldmbetcemnnhrdetuoahelfonenenistttainodogtsvfoenewrtvperteorrotomsuwgrdreruhcftmhtntceesaeoonhtoiantgrlaneuwtehsolamyiasgouaiofubsoleeeiiabefhniteesetettingassnymtcbfelrtfsytneteeinohllhtokieeshdencsaprodoenibrvnredoastiniwsivofrcabfodcohcuesteietoadohrmnetdmaearanrbaolruhmdhppswmccarrhtemnaefeaaeaaoehsihguatfirnsrfthfegiheiuleasahhanofuoselghrrsnredrorvrrhshtoisteurrcthineucahmieeeoeasfnuesiinsicfdfsonclmtwflhhheaoviaaeyeeerhsntofsneitanouuheqsriruweirermtydtfwasgreatlgbfdrmnokgegllsalhrumcpkfsoedfesucegertrtiytdnheeeloceveonuoueitrosinghfnufeoagsugaursisisesuaydaayurlass',
# Email 4 PlayFair no "J's"
    'edciohkidhngsdfldaepwfnhygnpryfwxfsfsyyqogodzddriegcrxgclfwfnwflakdosdeqmkforqkedrwiiwuypagpdangsttnwfdagcngwffpnwrcsyacsbgvuqfglywndfbssgdaxhekhbyouaostfdrvwgcsgucpgxosbdaxonldbxouasdnbxofxoidlsdtslsfadhdflsfkyqslfpfdslsggvfhslsyynqlaotswfgcoxtlkogfeqiexosefkfgrfrmnpnpeqkxdgkvdfsypnapsoigsocakgdfmkekwbrdrdxfsuhcdsrgqsygozwfdfdaygnpfapghlmkihtwxodsrwiadfflnckhpstlodbslfbqnbgdfuwoucrdodtffeykyqslbmuciggcdfbngdiegcwfaevwgcwfsliggcdfbngdiegcwfaevwgckhbntfbskhtfyrwbhfpykxdgkmgclssdgidcpkykbsgcfhkepslfrwoqiekgnwkhdawogtfywoucgigkscaungwuygtwogxfekardsxffylfsoqstflyihgcshdambakdgygbdwbsnda',
# Email 5 Hill 2x2 due the more large number bigram count/distribution 
    'cwxiyplxcwavpxxxilxuhwokprhogufhxtoaikilhorxjadgjnzopgoaaubpmxyyqvyegmfalivgyewadtoaaubpmxyyqvguxtllyvtcyvkckwbvyygvvjiqbcbkfavclxpnjcukfkeshjmplxyuubtnkenakqbcxyvjkggwgkrhgkjclxnwfkcyanssmgiathtvllhnouakoaantubkgcljbxjclxxkeawnfaweeewaxhbpsuxstvigglbcdybctubkryxuxcthdofjvjfazhnxryxuxcthdoouglrirrbywakpfjvjwkgvglbcdybctubkryxudotuncdosiakstfjryxudotuncdosiakstfjwwxshxzxtvglbcfazkwahnueiaubfakerizhtnxxrieasgrxjaglrkyytytvfawawnmgktceguiadxfkrrnajopuzgrknavjevcanxpwthbppstujadyjaglaivjtcigljqfbknxzcnayplxsggcwtrkmwbxnaovcghwxczxkpdhbpsudtmxuclifaxgrkglyeouaktvnantnjfclxsgtlzwhxglbcvlqtqgkt']

#counter = collections.Counter(emails[0])

""" #Print letter frequency distrution for each email
for i in range(5):
    print(i,collections.Counter(emails[i]))
"""
# English Bigram Freq.
ct = emails[0]
i = 0 # i starting char
print("Email 0",collections.Counter([ct[i:i+2] for i in range(0, len(ct), 2)]))  #grab every two char's w/in  the ct array and give count

ct1 = emails[4]
i = 0
print("Email 5", collections.Counter([ct1[i:i+2] for i in range(0,len(ct1), 2)]))
